# Generated by Django 5.1.1 on 2024-10-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='image_legend',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
