# Generated by Django 5.1.1 on 2024-10-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0005_alter_comment_user_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
